
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/garden.pnct \
    $(DIST)/garden.scene \

$(DIST)/garden.scene : garden.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "garden.blend:Collection" "$(DIST)/garden.scene"

$(DIST)/garden.pnct : garden.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "garden.blend:Collection" "$(DIST)/garden.pnct" 
